### ISSUE TITLE
Passing js libraries to Builder during deploy

### ISSUE THREAD

**Issue by leoedin** [electricimp/vscode#22]
Hi,

I've extended Builder with a javascript module, passed to pleasebuild with the --lib flag. This works well in our own build scripts, but the vscode extension uses its own instance of Builder and so we can't use the functionality in this library when doing deploys via the VSCode extension.

Is there a way to configure the vscode extension to pass libraries to the Builder instance? My understanding from the source code of this extension and Builder is that external libraries need to be passed into the Builder constructor - in which case I don't think there is a way. Hopefully I'm wrong!

If not, is it something you'd consider adding? It seems like a straightforward change - I can submit a PR if you'd consider accepting it.

Thanks!

**Comment by leoedin** [comment]
Looking through the old PRs,[ it appears that this has already been implemented](https://github.com/electricimp/vscode/pull/20) on the develop branch.

Is there any plans to make a release and update the version on the Visual Studio Code marketplace?

**Comment by terrencebarr** [comment]
Hi, we are working on aligning the resources for a VS Code update, but I can't give you a date yet.

Best,
-- Terrence

**Comment by leoedin** [comment]
Hi,

Is there any update on this? It would be great to not have to mess around with checking out git repos every time we set up a new dev environment.

**Comment by leoedin** [comment]
I should also add it appears that building the extension from source is broken due to outdated package dependencies. I've created a PR to fix this.
